name: "n8n"
version: "1.0.8"
slug: "n8n"
description: "Lance une instance de n8n pour l'automatisation des workflows"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
privileged:
  - NET_ADMIN  
  - SYS_ADMIN  
map:
  - ssh_keys:rw
  - addons:r
  - homeassistant_config:rw  
  - share:rw
  - ssl:rw
  
url: "https://github.com/echavet/n8n"
startup: "application"
boot: "auto"
host_network: true
ports:
  5678/tcp: 5678
ports_description:
  5678/tcp: "Port pour accéder à l'interface web de n8n"
options:
  log_level: "info"
schema:
  log_level: "list(debug|info|warn|error)?"
map:
  - "config:rw"  # Persistance des données dans /data
